name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main, develop, newTestBranch]

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          run: npm ci
            npm run test

  deploy-test:
    needs: test-ci
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          run: docker build -t nodejs-setup
            echo "Deploy"
  deploy-production:
    needs: test-ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          run: docker build -t nodejs-setup
            echo "Deploy"
