name: CI Tests

on: [push, pull_request]

jobs:
  test-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version:
      - run: npm ci
      - run: npm run test
